// 'Định nghĩa bộ nhận diện thương hiệu "Tổ Thẩm Định"';
export const styles = {
  app: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#f1f5f9",
    fontFamily: "'Inter', sans-serif",
  },
  sidebar: {
    width: "260px",
    backgroundColor: "#0f172a",
    color: "white",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
  },
  logo: {
    fontSize: "1.2rem",
    fontWeight: "bold",
    marginBottom: "32px",
    textAlign: "center",
    color: "#38bdf8",
    letterSpacing: "0.5px",
  },
  nav: { display: "flex", flexDirection: "column", gap: "10px" },
  navBtn: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    border: "none",
    backgroundColor: "transparent",
    color: "#94a3b8",
    cursor: "pointer",
    borderRadius: "8px",
    textAlign: "left",
    transition: "0.2s",
  },
  navActive: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px",
    border: "none",
    backgroundColor: "#1e293b",
    color: "#38bdf8",
    cursor: "pointer",
    borderRadius: "8px",
    textAlign: "left",
    fontWeight: "600",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
  mainContent: { flex: 1, overflowY: "auto", padding: "40px" },

  // Trạng thái hệ thống
  statusBar: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 24px",
    borderRadius: "10px",
    marginBottom: "24px",
    fontWeight: "500",
    fontSize: "14px",
  },
  ready: {
    backgroundColor: "#dcfce7",
    color: "#166534",
    border: "1px solid #bbf7d0",
  },
  loading: {
    backgroundColor: "#fef9c3",
    color: "#854d0e",
    border: "1px solid #fef08a",
  },
  error: {
    backgroundColor: "#fee2e2",
    color: "#991b1b",
    border: "1px solid #fecaca",
  },

  // Thanh tiến trình (ProgressBar)
  progressContainer: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "12px",
    marginBottom: "24px",
    border: "1px solid #e2e8f0",
  },
  progressHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "8px",
  },
  taskText: { fontSize: "13px", color: "#64748b", fontWeight: "600" },
  percentText: { fontSize: "13px", color: "#2563eb", fontWeight: "bold" },
  progressBgFull: {
    height: "8px",
    backgroundColor: "#f1f5f9",
    borderRadius: "4px",
    overflow: "hidden",
  },
  progressFillFull: {
    height: "100%",
    backgroundColor: "#3b82f6",
    transition: "width 0.4s ease-out",
  },

  // Khu vực tìm kiếm
  searchSection: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    backgroundColor: "white",
    padding: "24px",
    borderRadius: "16px",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05)",
  },
  textarea: {
    width: "100%",
    height: "100px",
    padding: "16px",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    resize: "none",
    fontSize: "15px",
    outline: "none",
  },
  btnPrimary: {
    backgroundColor: "#2563eb",
    color: "white",
    padding: "14px",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "15px",
  },

  // Kết quả (ResultCard)
  resultsContainer: {
    marginTop: "32px",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  resultCard: {
    backgroundColor: "white",
    borderRadius: "16px",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
    transition: "0.2s",
  },
  cardHeader: {
    padding: "16px 24px",
    borderBottom: "1px solid #f1f5f9",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fcfcfd",
  },
  rankBadge: {
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    padding: "4px 10px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "bold",
  },
  vattuTitle: {
    fontSize: "17px",
    fontWeight: "700",
    color: "#0f172a",
    margin: 0,
  },
  scoreBadge: {
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "bold",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr 1fr",
    gap: "20px",
    padding: "24px",
  },
  label: {
    fontSize: "11px",
    color: "#64748b",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  code: {
    backgroundColor: "#f8fafc",
    padding: "6px 10px",
    borderRadius: "6px",
    fontSize: "13px",
    fontFamily: "monospace",
  },
};
